/** @format */

const Data = [
  {
    title: "Gandhali Restaurant",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/1c/c1/28/09/resturants.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 400,
    minRs: 50,
    minTime: 30,
    rating: 4.0,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 1240,
    votes: 120,
  },
  {
    title: "Bansi Vihar",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/0c/16/b0/48/photo2jpg.jpg",
    description: "Indian, Asian",
    costForOne: 300,
    costForTwe: 600,
    minRs: 50,
    minTime: 30,
    rating: 3.4,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 520,
    votes: 100,
  },
  {
    title: "Biryani Mahal",
    imgUrl:
      "https://content3.jdmagicbox.com/comp/patna/x8/0612px612.x612.180605124354.q5x8/catalogue/biryani-mahal-kankarbagh-patna-mughlai-restaurants-ndrepaynn1.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 4.8,
    payment_methods: {
      card: false,
      cash: false,
      upi: true,
    },
    reviews: 240,
    votes: 60,
  },
  {
    title: "We are Back",
    imgUrl:
      "https://media-cdn.tripadvisor.com/media/photo-s/10/dd/d1/46/take-an-amazing-experience.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 500,
    minRs: 50,
    minTime: 30,
    rating: 3.2,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 1610,
    votes: 190,
  },
  {
    title: "Naan House",
    imgUrl:
      "https://www.blueosa.com/wp-content/uploads/2020/07/garlic-naam.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 800,
    minRs: 50,
    minTime: 30,
    rating: 3.2,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 1360,
    votes: 780,
  },
  {
    title: "Tibetan Food Tour of Majnu Ka Tilla",
    imgUrl:
      "https://cdn.vox-cdn.com/thumbor/Kp3g3wD1hSYgVXpr2Dha_CAe_Es=/0x0:960x640/720x540/filters:focal(404x244:556x396):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/65435097/DELHI_MAJNUKATILA.0.jpg",
    description: " Nepali, Asian, Desserts",
    cost: 1000,
    minRs: 50,
    minTime: 30,
    rating: 4.5,
    payment_methods: {
      card: false,
      cash: false,
      upi: true,
    },
    reviews: 160,
    votes: 25,
  },
  {
    title: "Noora Nihari",
    imgUrl:
      "https://cdn.vox-cdn.com/thumbor/HC5xKBjhPKiwFWs2Z1_izmqbchI=/0x0:1088x722/720x540/filters:focal(457x274:631x448):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/65435098/DELHI_HAJINOORA1.0.jpg",
    description: "Khameeri roti, Asian, Desserts",
    cost: 1200,
    minRs: 50,
    minTime: 30,
    rating: 4.9,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 1680,
    votes: 251,
  },
  {
    title: " Jung Bahadur Kachori Wala",
    imgUrl:
      "https://cdn.vox-cdn.com/thumbor/GEp1Ltk9nBIYzJrfupGCwS5LyaM=/0x0:869x736/720x540/filters:focal(366x299:504x437):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/65435101/Jung_Bahadur_Kachori_Wala_FB.0.jpg",
    description: "Continental, Pastries , Asian, Desserts",
    cost: 1450,
    minRs: 50,
    minTime: 30,
    rating: 5.0,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 680,
    votes: 311,
  },
  {
    title: "Chana Aloo Curry (Chickpea Potato Curry)",
    imgUrl:
      "https://www.spiceupthecurry.com/wp-content/uploads/2020/11/aloo-chana-recipe-2.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 1600,
    minRs: 50,
    minTime: 30,
    rating: 3.9,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 1980,
    votes: 291,
  },
  {
    title: "Shyam Sweets",
    imgUrl:
      "https://cdn.vox-cdn.com/thumbor/aYfIW83Y0_cZtZkeWDA86d82P0c=/0x0:4608x3456/720x540/filters:focal(913x1071:1649x1807):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/65435103/DELHI_SHYAMSWEETS1.0.jpg",
    description: "Bedmi Aloo, Asian, Desserts",
    cost: 120,
    minRs: 50,
    minTime: 30,
    rating: 4.1,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 2680,
    votes: 1401,
  },
  {
    title: "Prem Di Hatti",
    imgUrl:
      "https://cdn.vox-cdn.com/thumbor/T_sThFaq-7ufessI7jdXYWdzhYA=/0x0:4608x3248/720x540/filters:focal(1480x1216:2216x1952):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/65435105/DELHI_PREMDIHATTI.0.jpg",
    description: "Amritsari naan, Asian, Desserts",
    cost: 100,
    minRs: 50,
    minTime: 30,
    rating: 4.4,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 2580,
    votes: 291,
  },
  {
    title: "Masala Chai Expert",
    imgUrl:
      "https://www.blueosa.com/wp-content/uploads/2020/07/Classic-Indian-Masala-Chai-1024x705.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 60,
    minRs: 50,
    minTime: 30,
    rating: 3.5,
    payment_methods: {
      card: false,
      cash: false,
      upi: true,
    },
    reviews: 16080,
    votes: 2501,
  },
  {
    title: "Lassi House",
    imgUrl:
      "https://www.blueosa.com/wp-content/uploads/2020/07/Farm-to-table-cuisine-at-Blue-Osa-banana-smoothie.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 80,
    minRs: 50,
    minTime: 30,
    rating: 3.6,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 2680,
    votes: 291,
  },
  {
    title: "Elma's Bakery And Kitchen",
    imgUrl:
      "http://img.taste.com.au/wq_XowB-/taste/2016/11/top-50-cakes-image-17-66337-1.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: false,
      cash: false,
      upi: true,
    },
    reviews: 1980,
    votes: 751,
  },
  {
    title: "Defence Bakery",
    imgUrl:
      "https://d2jz4nqvi4omcr.cloudfront.net/Blogs/Best-Cake-Shops-Elmas.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 10680,
    votes: 251,
  },
  {
    title: " The Big Chill Cakery",
    imgUrl:
      "https://d2jz4nqvi4omcr.cloudfront.net/Blogs/Best-cake-shops-bigchill.jpg",
    description: "Continental, Cakes, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 2054,
    votes: 204,
  },
  {
    title: "Wengers",
    imgUrl:
      "https://d2jz4nqvi4omcr.cloudfront.net/Blogs/best-cake-shops-wengers.jpg",
    description: "Continental, Cakes, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 1780,
    votes: 102,
  },

  {
    title: " Pink Box",
    imgUrl:
      "https://lh3.googleusercontent.com/tRsEViklAwRqKPzxx7R3JrZU3xAyEfzexw5LbCZ4Ovb0_-ObHJPOouvrZ-vOtuwu1VPP2rvzs37H8APbSN6udKC_UZU=w1000",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: false,
      cash: false,
      upi: true,
    },
    reviews: 1780,
    votes: 101,
  },
  {
    title: "Chocolate mud cupcakes",
    imgUrl:
      "http://img.taste.com.au/a1EjasDr/taste/2016/11/top-50-cakes-image-6-66322-1.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: false,
      cash: true,
      upi: false,
    },
    reviews: 1480,
    votes: 601,
  },
  {
    title: "Basic sponge cake",
    imgUrl:
      "http://img.taste.com.au/I9GWGg53/taste/2016/11/top-50-cakes-image-9-66326-1.jpg",
    description: "Continental, Pizza, Asian, Desserts",
    cost: 600,
    minRs: 50,
    minTime: 30,
    rating: 2.0,
    payment_methods: {
      card: true,
      cash: false,
      upi: false,
    },
    reviews: 680,
    votes: 91,
  },
];

export default Data;
